# Generated by Django 4.0.6 on 2023-03-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='联系电话')),
                ('level', models.SmallIntegerField(choices=[(0, '初级学员'), (1, '高级学员'), (2, '初级花艺师'), (3, '高级花艺师'), (4, '店长')], verbose_name='员工级别')),
                ('hiredate', models.DateField(auto_now_add=True, verbose_name='入职日期')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本工资')),
                ('attendance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='全勤奖金')),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='绩效奖金')),
                ('meal_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='餐补')),
                ('manager_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='店长补贴')),
                ('welfare_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='福利补贴')),
                ('house_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='租房补贴')),
                ('other_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他补贴')),
                ('social_company', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='社保缴纳')),
                ('social_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='社保扣款')),
                ('on_job', models.SmallIntegerField(choices=[(1, '在职'), (0, '离职')], default=1, verbose_name='是否在职')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.store')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(max_length=32, unique=True, verbose_name='会员卡号')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='会员姓名')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='账户余额')),
            ],
        ),
        migrations.CreateModel(
            name='VipCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '消费'), (1, '充值')], default=0, verbose_name='费用类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='账户余额')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='费用发生时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.employee', verbose_name='操作员工')),
                ('vip_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.vip', verbose_name='会员编号')),
            ],
        ),
    ]
