# Generated by Django 4.0.6 on 2023-03-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_employee_vip_vipcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额'),
        ),
    ]
