# Generated by Django 4.0.6 on 2023-03-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_alter_vip_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='vipcost',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '消费'), (1, '充值')], verbose_name='费用类型'),
        ),
    ]
