# Generated by Django 4.0.6 on 2023-03-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_alter_vipcost_amount_alter_vipcost_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], verbose_name='订单状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('send', models.DateTimeField(verbose_name='配送时间')),
                ('send_type', models.SmallIntegerField(choices=[(0, '自提'), (1, '配送')], verbose_name='配送类型')),
                ('orderer', models.CharField(blank=True, max_length=32, null=True, verbose_name='订花人')),
                ('orderer_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='订花人电话')),
                ('consignee', models.CharField(blank=True, max_length=32, null=True, verbose_name='收花人')),
                ('consignee_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='收花人电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='收花地址')),
                ('product_type', models.SmallIntegerField(choices=[(0, '零花'), (1, '花束'), (2, '礼盒'), (3, '手提篮'), (4, '绿植'), (5, '开业花篮'), (6, '白事花圈'), (7, '布置：包厢、气球'), (8, '婚庆：手捧花、婚车'), (9, '其他类型')], verbose_name='产品类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已支付')),
                ('unpaid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='未支付')),
                ('paid_type', models.SmallIntegerField(choices=[(0, '现金'), (1, '微信'), (2, '收款码'), (3, '大众点评'), (4, '美团外卖'), (5, '饿了么'), (6, '公账'), (7, '会员卡'), (8, '其他')], verbose_name='付款方式')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='特别备注')),
                ('resource', models.SmallIntegerField(choices=[(0, '上门客'), (1, '微信'), (2, '美团'), (3, '大众点评'), (4, '美团外卖'), (5, '饿了么'), (6, '小程序'), (7, '地图'), (8, '其他')], verbose_name='订单来源')),
                ('add_wechat', models.SmallIntegerField(choices=[(0, '未添加'), (1, '已添加')], verbose_name='是否添加微信')),
                ('wechat_nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信名称')),
                ('rate', models.SmallIntegerField(choices=[(0, '未评价'), (1, '好评'), (2, '一般'), (3, '差评')], verbose_name='订单评价')),
                ('goods_image', models.ImageField(blank=True, null=True, upload_to='media/goods', verbose_name='订单照片')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/product', verbose_name='成品照片')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maker', to='flower.employee', verbose_name='制作员工')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='flower.employee', verbose_name='接单员工')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.store', verbose_name='所属门店')),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.vip', verbose_name='会员卡编号')),
            ],
        ),
    ]
