# Generated by Django 4.0.6 on 2023-03-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0007_alter_order_goods_image_alter_order_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配送时间'),
        ),
    ]
