# Generated by Django 4.0.6 on 2023-03-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0009_alter_order_goods_image_alter_order_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dianping',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='meituan',
            old_name='store_id',
            new_name='store',
        ),
    ]
