# Generated by Django 4.0.6 on 2023-03-26 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0010_rename_store_id_dianping_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('work', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='上班时长')),
                ('status', models.SmallIntegerField(choices=[(0, '全勤'), (1, '请假'), (2, '迟到'), (3, '旷工')], verbose_name='考勤状态')),
                ('time', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='时长')),
                ('comment', models.CharField(max_length=100, verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.employee', verbose_name='员工')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.store', verbose_name='门店')),
            ],
        ),
    ]
