# Generated by Django 4.0.6 on 2023-03-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0011_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='dianping',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.store', verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='meituan',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.store', verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flower.store', verbose_name='门店'),
        ),
    ]
